server:
  port: 9527

spring:
  application:
    name: SPRINGCLOUD-ROUTER-CONNECT-LOADBALANCE-HARDCODE-GATEWAY9527
  cloud:
    zookeeper:
      connect-string: 192.168.0.2:2181
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
