server:
  port: 80

spring:
    application:
        name: SPRINGCLOUD-CONSUMER-SLEUTH-ZIPKIN-LOADBALANCE-DEFAULT-ORDER80 #注意:服务名不要出现_
    devtools:
      restart:
        enabled: true
    logging:
      level: info
    cloud:
      zookeeper:
        connect-string: 192.168.0.2:2181
    zipkin:
      base-url: http://localhost:9411
    sleuth:
      sampler:
        probability: 1  # span的采样率，默认为 0.1,这个值介于0到1之间

#服务提供方信息
service:
  provider:
    name: SPRINGCLOUD-PROVIDER-SLEUTH-ZIPKIN-PAYMENT-SERVICE-CLUSTER  #服务提供方名称
    url: http://${service.provider.name} #服务提供方调用地址