server:
  port: 80

spring:
  application:
    name: SPRINGCLOUD-CONSUMER-LOADBALANCE-DEFAULT-ORDER80  #注意:服务名不要出现_
  devtools:
    restart:
      enabled: true
  logging:
    level: info
  cloud:
    zookeeper:
      connect-string: 192.168.0.2:2181

#服务提供方信息
service:
  provider:
    name: SPRINGCLOUD-PROVIDER-PAYMENT-SERVICE-CLUSTER  #服务提供方名称
    url: http://${service.provider.name} #服务提供方调用地址

